---
collections:
  - name: ansible.posix
  - name: kubernetes.core
  - name: community.docker
  - name: https://github.com/kubernetes-sigs/kubespray.git
    type: git
    version: v2.28.0  # The last version for RHEL 8
