---
collections:
  - name: ansible.posix
    version: 2.0.0
  - name: ansible.utils
    version: 5.1.2
  - name: kubernetes.core
    version: 5.2.0
  - name: community.docker
    version: 4.3.1
  - name: community.general
    version: 10.3.0
  - name: https://github.com/kubernetes-sigs/kubespray.git
    type: git
    version: v2.27.1  # Works with Alma 8 on VMWare
