---
collections:
  - name: ansible.posix
  - name: kubernetes.core
  - name: community.docker
  - name: community.kubernetes
  - name: https://github.com/kubernetes-sigs/kubespray.git
    type: git
    version: v2.25.1
