---
# These are inventory compatibility tasks with two purposes:
# - to ensure we keep compatibility with old style group names
# - to reduce inventory boilerplate (defining parent groups / empty groups)

- name: Define groups for legacy less structured inventories
  hosts: all
  gather_facts: false
  tags: always
  tasks:
    - name: Match needed groups by their old names or definition
      vars:
        group_mappings:
          kube_control_plane:
            - k8s_masters
          kube_node:
            - k8s_nodes
          calico_rr:
            - calico-rr
          no_floating:
            - no-floating
          k8s_cluster:
            - kube_node
            - kube_control_plane
            - calico_rr
      ansible.builtin.group_by:
        key: "{{ (group_names | intersect(item.value) | length > 0) | ternary(item.key, '_all') }}"
      loop: "{{ group_mappings | dict2items }}"
