#!/usr/bin/env ansible-playbook
---
- name: Common
  hosts: all:!localhost:!bastion
  become: true
  gather_facts: false
  pre_tasks:
    - name: Set hostname
      ansible.builtin.hostname:
        name: "{{ inventory_hostname }}"

- name: Install Kubernetes
  become: true
  ansible.builtin.import_playbook: kubernetes_sigs.kubespray.cluster
  tags: kubernetes
