#!/usr/bin/env ansible-playbook
---
# ~/.kube/config should be valid
- name: Manage KubeBlocks
  hosts: localhost
  become: false
  tasks:
    - name: Install KubeBlocks
      ansible.builtin.include_role:
        name: bbaassssiiee.kubeblocks

    - name: Configure KubeBlocks
      ansible.builtin.include_role:
        name: clusterlust.kubeblocks
