#!/usr/bin/env ansible-playbook
---
# ~/.kube/config should be valid
- name: Manage KubeBlocks
  hosts: localhost
  become: false
  vars:
    # Semaphore does not pass $HOME so path needs to be set explicitly.
    k8s_auth_kubeconfig: /home/semapphore/.kube/config
  tasks:
    - name: Install KubeBlocks
      ansible.builtin.include_role:
        name: bbaassssiiee.kubeblocks

    - name: Configure KubeBlocks
      ansible.builtin.include_role:
        name: clusterlust.kubeblocks
