#!/usr/bin/env ansible-playbook
---
- name: Install kbcli
  hosts: controller
  become: true
  tasks:
    - name: Configure KubeBlocks
      when: desired_state == 'present'
      ansible.builtin.include_role:
        name: clusterlust.kbcli

- name: Manage KubeBlocks
  hosts: localhost
  become: false
  connection: local
  vars:
    # Semaphore does not pass $HOME so K8S_AUTH_KUBECONFIG needs to be set.
    k8s_auth_kubeconfig: /home/semaphore/.kube/config
    # To manage KubeBlocks addons set this Boolean
    # use_kb_addons: true
  tasks:
    - name: Configure KubeBlocks
      ansible.builtin.include_role:
        name: clusterlust.kubeblocks

- name: Remove kbcli
  hosts: controller
  become: true
  tasks:
    - name: Configure KubeBlocks
      when: desired_state == 'absent'
      ansible.builtin.include_role:
        name: clusterlust.kbcli
