#!/usr/bin/env ansible-playbook
---

- name: Disable firewall
  hosts: k8s_cluster:proxy
  become: true
  gather_facts: false
  pre_tasks:
    - name: Disable firewalld
      ansible.builtin.systemd:
        name: firewalld
        state: stopped
        enabled: false


- name: Install squid on proxy host
  hosts: proxy
  become: true
  gather_facts: false

  tasks:

    - name: Gathering facts
      ansible.builtin.setup:
        gather_subset: platform

    - name: Install docker-ce
      ansible.builtin.import_role:
        name: geerlingguy.docker
      tags: [docker]

    - name: Install Squid proxy
      ansible.builtin.import_role:
        name: proxy
      tags: [proxy]

- name: Enable proxy
  hosts: k8s_cluster
  become: true
  gather_facts: false
  tags: [proxy]
  tasks:
    - name: Fix dnf
      ansible.builtin.lineinfile:
        path: /etc/dnf/dnf.conf
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        state: present
      loop:
        - regexp: '^proxy='
          line: "proxy={{ http_proxy | default('') }}"
        - regexp: '^repo_gpgcheck='
          line: 'repo_gpgcheck=0'
