#!/usr/bin/env ansible-playbook
---

- name: Disable firewall
  hosts: k8s_cluster
  become: true
  gather_facts: false
  pre_tasks:
    - name: Disable firewalld
      ansible.builtin.systemd:
        name: firewalld
        state: stopped
        enabled: false

    - name: Fix dnf
      ansible.builtin.lineinfile:
        path: /etc/dnf/dnf.conf
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        state: present
      loop:
        - regexp: '^proxy='
          line: "proxy={{ http_proxy | default('') }}"
        - regexp: '^repo_gpgcheck='
          line: 'repo_gpgcheck=0'
