#!/usr/bin/env ansible-playbook
---
- name: Common tasks for every playbooks
  import_playbook: boilerplate.yml

- name: Reset cluster
  hosts: etcd:k8s_cluster:calico_rr
  gather_facts: true
  become: true

  collections:
    - kubernetes_sigs.kubespray

  tasks:
    - name: Set Kubespray defaults
      ansible.builtin.include_role:
        name: kubespray-defaults

    - name: Kubeadm reset with force
      ansible.builtin.command:
        cmd: kubeadm reset -f
      changed_when: true
      register: _reset
      failed_when: _reset.rc not in [0, 2]

    - name: Run Kubespray reset role
      ansible.builtin.include_role:
        name: reset
      vars:
        bin_dir: /usr/bin
        containerd_storage_dir: "/var/lib/containerd"
        containerd_state_dir: "/run/containerd"
        containerd_systemd_dir: "/etc/systemd/system/containerd.service.d"
        containerd_cfg_dir: "/etc/containerd"
        sysctl_file_path: "/etc/sysctl.d/99-sysctl.conf"
        deploy_container_engine: true
        etcd_config_dir: /etc/ssl/etcd
        etcd_data_dir: /var/lib/etcd
        etcd_events_data_dir: /var/lib/etcd-events
        enable_dual_stack_networks: false
        ipv4_stack: true
        ipv6_stack: false
        kube_config_dir: /etc/kubernetes
        krew_root_dir: /usr/local/krew
        nginx_config_dir: /etc/nginx

    - name: Remove /etc/cni/net.d
      ansible.builtin.file:
        path: /etc/cni/net.d
        state: absent

- name: Reset cluster
  hosts: k8s_cluster
  gather_facts: true

  tasks:
    - name: Clear kube config dir
      become: true
      ansible.builtin.file:
        path: /root/.kube
        state: absent

    - name: Clear /etc/kubernetes
      become: true
      ansible.builtin.file:
        path: /etc/kubernetes
        state: absent

    - name: Reboot
      become: true
      ansible.builtin.reboot:
