---
# Tasks to remove CA Issuer and related resources
- name: Remove ConfigMap ca-config
  kubernetes.core.k8s:
    state: absent
    api_version: v1
    kind: ConfigMap
    name: ca-config
    namespace: cert-manager

- name: Remove ClusterIssuer ca-issuer
  kubernetes.core.k8s:
    state: absent
    api_version: cert-manager.io/v1
    kind: ClusterIssuer
    name: ca-issuer

- name: Remove CA Certificate (ca-cert)
  kubernetes.core.k8s:
    state: absent
    api_version: cert-manager.io/v1
    kind: Certificate
    name: ca-cert
    namespace: cert-manager

- name: Remove secret ca-key-pair (CA private key & cert)
  kubernetes.core.k8s:
    state: absent
    api_version: v1
    kind: Secret
    name: ca-key-pair
    namespace: cert-manager

- name: Remove ClusterIssuer bootstrap-ca
  kubernetes.core.k8s:
    state: absent
    api_version: cert-manager.io/v1
    kind: ClusterIssuer
    name: bootstrap-ca
