---
# Main tasks entry point for the role
- name: "Converge state - {{ desired_state }}"
  ansible.builtin.include_tasks: "{{ desired_state }}.yml"

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: "Verify state - {{ desired_state }}"
  ansible.builtin.include_tasks: verify.yml
  when: desired_state != "absent"
