---
- name: Check offline status
  ansible.builtin.debug:
    msg: "registry_user: {{ registry_user | d('') }}"
    verbosity: 2

- name: Registry login
  become: true
  become_user: semaphore
  when: registry_pass is defined
  environment:
    REGISTRY_PASS: "{{ registry_pass }}"
  ansible.builtin.command:
    cmd: 'docker login -u="{{ registry_user }}" -p=$REGISTRY_PASS "{{ registry_host }}"'
    creates: "{{ lookup('env', 'HOME')/.docker/config.json"
