---
- name: Find kbcli release
  when: kbcli_download_url is not defined
  become: false
  block:

    - name: Get kbcli Release info from Github
      ansible.builtin.uri:
        url: "{{ kbcli_releases_url }}"
        return_content: true
        body_format: json
      register: _sem_rel
      check_mode: false

    - name: Set kbcli requirements
      ansible.builtin.set_fact:
        kbcli_version: "{{ _sem_rel['json']['tag_name'][1:] }}"
        kbcli_pkg_ext: "{{ (ansible_facts['os_family'] == 'RedHat') | ternary('rpm', 'deb') }}"
        kbcli_pkg_arch: "{{ (ansible_facts['architecture'] == 'x86_64') | ternary('amd64', 'arm64') }}"

    - name: Set kbcli_download_url
      ansible.builtin.set_fact:
        kbcli_download_url: "{{ kbcli_repo_url }}/{{ _sem_rel.json.name }}/kbcli-linux-{{ kbcli_pkg_arch }}-v{{ kbcli_version }}.{{ kbcli_pkg_ext }}"

- name: Install kbcli package
  when: kbcli_download_package | bool
  block:

    - name: Download kbcli
      become: false
      ansible.builtin.get_url:
        url: "{{ kbcli_download_url }}"
        dest: "/tmp/kbcli.{{ kbcli_pkg_ext }}"
        mode: '0644'
      register: downloaded_kbcli

    # This task will be skipped in check mode
    - name: Ensure kbcli installed
      become: true
      ansible.builtin.dnf:
        name: "file:///tmp/kbcli.{{ kbcli_pkg_ext }}"
        disable_gpg_check: true
        state: present
      when:
        - not ansible_check_mode
        - downloaded_kbcli is success
        - ansible_facts['os_family'] == 'RedHat'

    # This task will be skipped in check mode
    - name: Ensure kbcli installed
      become: true
      ansible.builtin.apt:
        deb: "file:///tmp/kbcli.{{ kbcli_pkg_ext }}"
        allow_unauthenticated: true
        state: present
      when:
        - not ansible_check_mode
        - downloaded_kbcli is success
        - ansible_facts['os_family'] == 'Debian'

  always:
    - name: Remove package from /tmp
      ansible.builtin.file:
        path: "/tmp/kbcli.{{ kbcli_pkg_ext }}"
        state: absent
