---
# when: desired_state == 'present'
- name: Install KubeBlocks
  when: use_kubeblocks | bool
  ansible.builtin.include_tasks: "kubeblocks.yml"

- name: Manage KubeBlocks Add-ons
  when: use_kb_addons | bool
  ansible.builtin.include_tasks: "addons.yml"
  loop: "{{ kubeblocks_add_ons }}"
