---
- name: Ensure policy render destination exists
  ansible.builtin.file:
    path: "{{ policy_render_dest_dir }}"
    state: directory
    mode: '0755'

- name: Prepare Kyverno install manifest
  when: kyverno_install | bool
  ansible.builtin.copy:
    src: "kyverno-install.yaml"
    dest: "{{ policy_render_dest_dir }}/kyverno-install.yaml"
    mode: '0644'

- name: Apply Kyverno install manifest
  when: kyverno_install | bool
  ansible.builtin.shell:
    cmd: "kubectl create -f {{ policy_render_dest_dir }}/kyverno-install.yaml"
  ignore_errors: true

- name: Wait for Kyverno CRDs to be ready
  kubernetes.core.k8s_info:
    api_version: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: clusterpolicies.kyverno.io
    kubeconfig: "{{ kubeconfig | default(omit) }}"
  register: kyverno_crd
  until: kyverno_crd.resources | length > 0
  retries: 30
  delay: 5
